[package]
name = "miniserde-from-value"
version = "0.1.0"
authors = ["etwyniel <etwyniel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miniserde = "0.1"
